version: '3.8'
name: forum_dev

services:
  forum_api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=${VIRTUAL_HOST:-forum.dorkodu.com}
      - VIRTUAL_PORT=${API_PORT:-8003}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-forum.dorkodu.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-hey@dorkodu.com}
      - VIRTUAL_PATH=/api
    expose:
      - ${API_PORT:-8003}
    volumes:
      - ./api:/forum/api
      - api_node_modules:/forum/api/node_modules
    restart: always
    networks:
      - app
      - nginx-proxy

  forum_web:
    build:
      context: .
      dockerfile: ./web/Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=${VIRTUAL_HOST:-forum.dorkodu.com}
      - VIRTUAL_PORT=${WEB_PORT:-8002}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-forum.dorkodu.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-hey@dorkodu.com}
      - VIRTUAL_PATH=/
    expose:
      - ${WEB_PORT:-8002}
    volumes:
      - ./web:/forum/web
      - ./api:/forum/api
      - web_node_modules:/forum/web/node_modules
    restart: always
    networks:
      - app
      - nginx-proxy

  forum_postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-forum}
      - PGPORT=${PGPORT:-7001}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app

  forum_keydb:
    image: eqalpha/keydb:x86_64_v6.3.1
    volumes:
      - ./keydb/keydb.conf:/etc/keydb/keydb.conf
    restart: always
    networks:
      - app

volumes:
  pgdata:
  api_node_modules:
  web_node_modules:

networks:
  nginx-proxy:
    external: true
  app: