version: '3.8'
name: forum_dev

services:
  forum_next:
    build:
      context: .
      dockerfile: ./next/Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=${VIRTUAL_HOST:-forum.dorkodu.com}
      - VIRTUAL_PORT=${PORT:-8001}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-forum.dorkodu.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-hey@dorkodu.com}
    expose:
      - ${PORT:-8001}
    volumes:
      - ./next:/forum/next
      - next_node_modules:/forum/next/node_modules
    restart: always
    networks:
      - app
      - nginx-proxy

  forum_postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-forum}
      - PGPORT=${PGPORT:-7001}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app

  forum_keydb:
    image: eqalpha/keydb:x86_64_v6.3.1
    volumes:
      - ./keydb/keydb.conf:/etc/keydb/keydb.conf
    restart: always
    networks:
      - app

volumes:
  pgdata:
  next_node_modules:

networks:
  nginx-proxy:
    external: true
  app: