FROM node:16.17.1-alpine
WORKDIR /forum

RUN mkdir -p /forum/api

RUN npm install -g pnpm && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

COPY ./api/pnpm-lock.yaml /forum/api
RUN cd api && pnpm fetch --no-frozen-lockfile
COPY ./api /forum/api
RUN cd api && pnpm install --offline

WORKDIR /forum/api
CMD [ "pnpm", "run", "dev" ]