FROM node:16.17.1-alpine as base
WORKDIR /cherno

RUN mkdir -p /cherno/web
RUN mkdir -p /cherno/api

RUN npm install -g pnpm && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

WORKDIR /cherno/web

COPY ./web/pnpm-lock.yaml /cherno/web
COPY ./api/pnpm-lock.yaml /cherno/api
RUN cd /cherno/web && pnpm fetch && cd /cherno/api && pnpm fetch
COPY ./web /cherno/web
COPY ./api /cherno/api
RUN cd /cherno && pnpm install -r --offline

#RUN pnpm test
RUN pnpm build