FROM node:16.17.1-alpine
WORKDIR /forum

RUN mkdir -p /forum/web
RUN mkdir -p /forum/api

RUN npm install -g pnpm && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

COPY ./web /forum/web
COPY ./api /forum/api
RUN cd /forum/web && pnpm install && cd /forum/api && pnpm install

WORKDIR /forum/web
CMD [ "pnpm", "run", "dev" ]